name: sanitybuild Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress First Test
        uses: cypress-io/github-action@v6
        with:
            command: npm run secondTest

      - name: Cypress repots
        uses: actions/upload-artifact@v3
        with:
             name: mochawsome HTML report - Secondtest report
             path: cypress/reports/html/
         
           
  assertions-run:
                  runs-on: ubuntu-22.04
                  steps:
                    - name: Checkout - two tests report

                      uses: actions/checkout@v4
                    # Install npm dependencies, cache them correctly
                    # and run all Cypress tests
                    - name: Cypress run
                      uses: cypress-io/github-action@v6
                      with:
                          command: npm run run:twotests 
                    - name: Cypress repots
                      if: always()
                      uses: actions/upload-artifact@v3
                      with:
                               name: mochawsome HTML report
                               path: cypress/reports/html/
                  

            
            
            